---
# tasks file for ansible-es

- name: "Install packages"
  ansible.builtin.include_tasks: "packages-{{ ansible_os_family }}.yml"

# ES configuration:
# - Most settings in /etc/elasticsearch/elasticsearch.yml
# - Heap size needs to be configured in jvm.options
#   https://www.elastic.co/guide/en/elasticsearch/reference/6.8/heap-size.html

- name: Update ES config files (/etc/elasticsearch/)
  ansible.builtin.template:
    src: etc/elasticsearch/{{ item }}.j2
    dest: /etc/elasticsearch/{{ item }}
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  loop:
    - elasticsearch.yml
    - jvm.options
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)

# Need a systemd config override to allow memory locking by ES
- name: Block to configure systemd config override
  block:
    - name: Create systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Configure elasticsearch systemd override (LimitMEMLock)
      ansible.builtin.template:
        src: etc/systemd/system/elasticsearch.service.d/override.conf.j2
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart systemd elasticsearch service (with daemon-reload)
