---
# tasks file for ansible-es

- name: "Install packages"
  ansible.builtin.include_tasks: "packages-{{ ansible_os_family }}.yml"

# ES configuration:
# - Most settings in /etc/elasticsearch/elasticsearch.yml
# - Heap size needs to be configured in jvm.options
#   https://www.elastic.co/guide/en/elasticsearch/reference/6.8/heap-size.html

- name: Update jvm.options
  ansible.builtin.template:
    src: etc/elasticsearch/jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)

- name: Update elasticsearch.yml
  ansible.builtin.template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)
  register: _es_yml_templ_result
  tags: es-repo

# Need a systemd config override to allow memory locking by ES
- name: Block to configure systemd config override
  block:
    - name: Create systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Configure elasticsearch systemd override (LimitMEMLock)
      ansible.builtin.template:
        src: etc/systemd/system/elasticsearch.service.d/override.conf.j2
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart systemd elasticsearch service (with daemon-reload)

# Configure snapshot repositories if defined
- name: Ensure directory to hold repository exists
  ansible.builtin.file:
    path: "{{ es_snapshot_repository.location }}"
    state: directory
    mode: "0755"
    owner: elasticsearch
    group: elasticsearch
  when:
    - es_snapshot_repository is defined
  tags: es-repo

- name: Configure snapshot repositories block
  when:
    - es_path_repo is defined
    - es_snapshot_repository is defined
    - _es_yml_templ_result is changed
  tags: es-repo
  block:
    - name: Flush to restart elasticsearch if there were config changes
      ansible.builtin.meta: "flush_handlers"

    - name: Wait until elasticsearch service is up
      ansible.builtin.wait_for:
        port: 9200
        timeout: 120

    - name: Register ES repository
      ansible.builtin.uri:
        url: "http://127.0.0.1:9200/_snapshot/{{ es_snapshot_repository.name }}"
        method: PUT
        body:
          type: fs
          settings:
            location: "{{ es_snapshot_repository.location }}"
        body_format: json

- name: Ensure elasticsearch service is enabled
  ansible.builtin.systemd_service:
    enabled: true
    name: elasticsearch
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)
